### ISSUE TITLE
Error after close DB client

### ISSUE THREAD

**Issue by Lupen2002** [couchbase/couchbase-lite-java#52] opened 2015-02-19 06:55 UTC
```java
private void shutdownDatabase() {
        push.goOffline();
        pull.goOffline();
        pull.stop();
        push.stop();
        database.close();
        manager.close();
    }
````
in log:
```
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@32f4b68 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@5263919f[Shutting down, pool size = 1, active threads = 1, queued tasks = 6, completed tasks = 15]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:632)
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:678)
	at com.couchbase.lite.replicator.PullerInternal.changeTrackerStopped(PullerInternal.java:766)
	at com.couchbase.lite.replicator.ChangeTracker.stopped(ChangeTracker.java:512)
	at com.couchbase.lite.replicator.ChangeTracker.stop(ChangeTracker.java:498)
	at com.couchbase.lite.replicator.PullerInternal.goOffline(PullerInternal.java:994)
	at com.couchbase.lite.replicator.ReplicationInternal$15.doIt(ReplicationInternal.java:1101)
	at com.couchbase.lite.replicator.ReplicationInternal$15.doIt(ReplicationInternal.java:1098)
	at com.github.oxo42.stateless4j.StateConfiguration$3.doIt(StateConfiguration.java:130)
	at com.github.oxo42.stateless4j.StateConfiguration$3.doIt(StateConfiguration.java:127)
	at com.github.oxo42.stateless4j.StateRepresentation.executeEntryActions(StateRepresentation.java:123)
	at com.github.oxo42.stateless4j.StateRepresentation.enter(StateRepresentation.java:102)
	at com.github.oxo42.stateless4j.StateMachine.publicFire(StateMachine.java:199)
	at com.github.oxo42.stateless4j.StateMachine.fire(StateMachine.java:125)
	at com.couchbase.lite.replicator.ReplicationInternal$1.run(ReplicationInternal.java:191)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@4579bbfb rejected from java.util.concurrent.ScheduledThreadPoolExecutor@5263919f[Shutting down, pool size = 1, active threads = 1, queued tasks = 3, completed tasks = 18]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:632)
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:678)
	at com.couchbase.lite.replicator.ReplicationInternal.notifyChangeListeners(ReplicationInternal.java:983)
	at com.couchbase.lite.replicator.ReplicationInternal.notifyChangeListenersStateTransition(ReplicationInternal.java:1138)
	at com.couchbase.lite.replicator.ReplicationInternal.access$400(ReplicationInternal.java:61)
	at com.couchbase.lite.replicator.ReplicationInternal$16.doIt(ReplicationInternal.java:1109)
	at com.couchbase.lite.replicator.ReplicationInternal$16.doIt(ReplicationInternal.java:1105)
	at com.github.oxo42.stateless4j.StateRepresentation.executeExitActions(StateRepresentation.java:130)
	at com.github.oxo42.stateless4j.StateRepresentation.exit(StateRepresentation.java:112)
	at com.github.oxo42.stateless4j.StateMachine.publicFire(StateMachine.java:197)
	at com.github.oxo42.stateless4j.StateMachine.fire(StateMachine.java:125)
	at com.couchbase.lite.replicator.ReplicationInternal$1.run(ReplicationInternal.java:191)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by hideki** [comment] 2015-02-19 07:03
@Lupen2002 Thank you for reporting the issue.

Could you please provide us version number or how did you get CBL Java?

**Comment by Lupen2002** [comment] 2015-02-19 07:25
1.0.3

**Comment by Lupen2002** [comment] 2015-02-19 07:52
I'm sorry with this code:
```java
private void shutdownDatabase() {
        push.goOffline();
        pull.goOffline();
        pull.stop();
        push.stop();
        database.close();
        manager.close();
    }
```
my the application does not close.
in log:
```
12:49:48.292 [CBLRequestWorker-26393-0] ERROR com.couchbase.lite - Sync: com.couchbase.lite.replicator.ReplicationInternal$4@4bdf08cc checkSessionAtPath() response: {authentication_handlers=[default, cookie], ok=true, userCtx={channels={*=1}, name=null}}
12:49:48.292 [CBLRequestWorker-0c6a4-0] ERROR com.couchbase.lite - Sync: com.couchbase.lite.replicator.ReplicationInternal$4@34da9d3 checkSessionAtPath() response: {authentication_handlers=[default, cookie], ok=true, userCtx={channels={*=1}, name=null}}
12:49:48.319 [Thread-3] ERROR com.couchbase.lite - Sync: PullerInternal stopGraceful.run() finished
12:49:48.367 [main] INFO  o.s.w.s.m.m.a.RequestMappingHandlerMapping - Mapped "{[/error],methods=[],params=[],headers=[],consumes=[],produces=[text/html],custom=[]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest)
12:49:48.367 [main] INFO  o.s.w.s.m.m.a.RequestMappingHandlerMapping - Mapped "{[/error],methods=[],params=[],headers=[],consumes=[],produces=[],custom=[]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
12:49:49.353 [http-nio-8080-exec-2] ERROR c.c.mobicat.server.info.VersionInfo - Version info not found
12:49:49.354 [http-nio-8080-exec-2] ERROR c.c.mobicat.server.info.VersionInfo - Version info not found
12:49:55.869 [Thread-6] INFO  com.centreit.mobicat.server.Runner - Google Chrome Error Output завершён
12:49:55.887 [CBLRequestWorker-0c6a4-1] ERROR com.couchbase.lite - Sync: com.couchbase.lite.replicator.ReplicationInternal$4@165ad19b checkSessionAtPath() response: {authentication_handlers=[default, cookie], ok=true, userCtx={channels={*=1}, name=null}}
12:49:55.901 [CBLManagerWorkExecutor] ERROR com.couchbase.lite - Sync: Change tracker stopped during continuous replication
12:49:55.902 [Thread-6] ERROR com.couchbase.lite - StorageEngine: Close: Error (5) closing database
12:49:55.902 [CBLRequestWorker-0c6a4-1] ERROR com.couchbase.lite - Sync: com.couchbase.lite.replicator.ReplicationInternal$4@165ad19b Exception in checkSessionAtPath()
12:49:55.903 [Thread-13] ERROR com.couchbase.lite - Sync: PusherInternal stopGraceful.run() finished
12:49:55.904 [Thread-12] ERROR com.couchbase.lite - Sync: PullerInternal stopGraceful.run() finished
12:49:55.912 [CBLManagerWorkExecutor] ERROR com.couchbase.lite - Sync: Change tracker stopped during continuous replication
```

**Comment by Lupen2002** [comment] 2015-02-19 12:20
maybe CBLRequestWorker create daedlock after closing?

**Comment by hideki** [comment] 2015-02-19 19:35
Thank you for your updates. I will investigate the issue.

Followings may not be related with this issue. 

If you call `Manager.close()`, you don't need to call `replicator.goOffline()`, `replicator.close()` and `database.close()`.

`Mager.close()`
```
public void close() {
        Log.i(Database.TAG, "Closing " + this);
        for (Database database : databases.values()) {
            List<Replication> replicators = database.getAllReplications();
            if (replicators != null) {
                for (Replication replicator : replicators) {
                    replicator.stop();
                }
            }
            database.close();
        }
        databases.clear();
        context.getNetworkReachabilityManager().stopListening();
        Log.i(Database.TAG, "Closed " + this);
    }
```

**Comment by Lupen2002** [comment] 2015-02-20 06:31
thank you. but my app does not close. beсause threads CBLRequestWorker in status wait.

**Comment by hideki** [comment] 2015-02-20 07:53
Ticket will be tracked by couchbase-lite-java-core
https://github.com/couchbase/couchbase-lite-java-core/issues/452

**Comment by hideki** [comment] 2015-03-06 00:17
Hi @Lupen2002 

I could reproduce this issue with CBL Java release/1.0.3 branch. However, the issue is no longer reproducible with master branch. If this issue is critical for you, please use master branch code instead of 1.0.3?

This is Unit Test code to reproduce this issue.
https://github.com/couchbase/couchbase-lite-android/commit/e9d8593d998fa7d3d8d51ea9ecf9fe9fe45d0121

Thanks,
Hideki

**Comment by hideki** [comment] 2015-03-06 00:28
Note to self:

Once uni test [PR](https://github.com/couchbase/couchbase-lite-android/pull/539) is merged, close this ticket.

**Comment by Lupen2002** [comment] 2015-03-06 07:41
Ok. I want substitute couchbase-lite-java or couchbase-lite-java-core?

**Comment by hideki** [comment] 2015-03-06 07:58
> Ok. I must substitute couchbase-lite-java or couchbase-lite-java-core?

couchbase-lite-java-core

**Comment by Lupen2002** [comment] 2015-03-06 08:02
I installed libraries from master branch, but application process does not die. my logs before closing my app:
```
12:53:07.778 [Thread-9] WARN  com.couchbase.lite - Sync: [fireTrigger()] => GO_OFFLINE
12:53:07.778 [Thread-9] WARN  com.couchbase.lite - Sync: [fireTrigger()] => GO_OFFLINE
12:53:07.778 [Thread-9] WARN  com.couchbase.lite - Sync: [fireTrigger()] => STOP_GRACEFUL
12:53:07.778 [CBLManagerWorkExecutor] INFO  c.g.oxo42.stateless4j.StateMachine - Firing GO_OFFLINE
12:53:07.778 [Thread-9] WARN  com.couchbase.lite - Sync: [fireTrigger()] => STOP_GRACEFUL
12:53:07.778 [Thread-9] WARN  com.couchbase.lite - Sync: [fireTrigger()] => STOP_GRACEFUL
12:53:07.778 [Thread-9] WARN  com.couchbase.lite - Sync: [fireTrigger()] => STOP_GRACEFUL
12:53:07.779 [CBLManagerWorkExecutor] INFO  c.g.oxo42.stateless4j.StateMachine - Firing GO_OFFLINE
12:53:07.779 [Thread-9] INFO  com.couchbase.lite - CBLite: Closing com.couchbase.lite.Manager@33ddfc44
12:53:07.779 [Thread-9] INFO  com.couchbase.lite - CBLite: Closed com.couchbase.lite.Manager@33ddfc44
12:53:07.779 [CBLManagerWorkExecutor] INFO  c.g.oxo42.stateless4j.StateMachine - Firing STOP_GRACEFUL
12:53:07.780 [ChangeTracker-http://localhost:4984/mobicat/] WARN  com.couchbase.lite - ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@270f8023: Change tracker calling changeTrackerStopped, client: com.couchbase.lite.replicator.PullerInternal@3134b194
12:53:07.780 [CBLManagerWorkExecutor] WARN  com.couchbase.lite - Sync: [fireTrigger()] => RESUME
12:53:07.780 [Thread-9] INFO  o.s.c.s.DefaultLifecycleProcessor - Stopping beans in phase 2147483647
12:53:07.781 [Thread-9] INFO  o.s.m.s.b.SimpleBrokerMessageHandler - Stopping...
12:53:07.781 [Thread-9] INFO  o.s.m.s.b.SimpleBrokerMessageHandler - BrokerAvailabilityEvent[available=false, SimpleBroker[DefaultSubscriptionRegistry[cache[0 destination(s)], registry[0 sessions]]]]
12:53:07.781 [Thread-9] INFO  o.s.m.s.b.SimpleBrokerMessageHandler - Stopped.
12:53:07.781 [Thread-9] INFO  o.s.j.e.a.AnnotationMBeanExporter - Unregistering JMX-exposed beans on shutdown
12:53:07.782 [CBLManagerWorkExecutor] INFO  c.g.oxo42.stateless4j.StateMachine - Firing STOP_GRACEFUL
12:53:07.782 [CBLManagerWorkExecutor] WARN  com.couchbase.lite - Sync: com.couchbase.lite.replicator.PullerInternal@3134b194: starting ChangeTracker with since=66123 mode=OneShot
12:53:07.782 [CBLManagerWorkExecutor] WARN  com.couchbase.lite - Sync: com.couchbase.lite.replicator.PullerInternal@3134b194: started ChangeTracker com.couchbase.lite.replicator.ChangeTracker@1f15768a
12:53:07.783 [Thread-19] WARN  com.couchbase.lite - Sync: [fireTrigger()] => STOP_IMMEDIATE
12:53:07.783 [ChangeTracker-http://localhost:4984/mobicat/] ERROR com.couchbase.lite - ChangeTracker: Thread id => 97
12:53:07.789 [Thread-9] INFO  o.s.s.c.ThreadPoolTaskExecutor - Shutting down ExecutorService 'brokerChannelExecutor'
12:53:07.790 [Thread-9] INFO  o.s.s.c.ThreadPoolTaskScheduler - Shutting down ExecutorService 'messageBrokerSockJsTaskScheduler'
12:53:07.790 [CBLRequestWorker-0c6a4-0] WARN  com.couchbase.lite - RemoteRequest: RemoteRequest Unable to parse user info, not setting credentials
12:53:07.796 [Thread-9] INFO  o.s.s.c.ThreadPoolTaskExecutor - Shutting down ExecutorService 'clientOutboundChannelExecutor'
12:53:07.796 [CBLManagerWorkExecutor] DEBUG c.c.m.s.s.couchbase.CouchbaseService - push event: PUSH replication event. Source: com.couchbase.lite.replicator.Replication@1224b507 Transition: IDLE -> OFFLINE Total changes: 0 Completed changes: 0
12:53:07.796 [CBLManagerWorkExecutor] INFO  c.g.oxo42.stateless4j.StateMachine - Firing STOP_GRACEFUL
12:53:07.796 [Thread-9] INFO  o.s.s.c.ThreadPoolTaskExecutor - Shutting down ExecutorService 'clientInboundChannelExecutor'
12:53:07.796 [CBLManagerWorkExecutor] INFO  c.g.oxo42.stateless4j.StateMachine - Firing STOP_GRACEFUL
12:53:07.797 [CBLManagerWorkExecutor] DEBUG c.c.m.s.s.couchbase.CouchbaseService - push event: PUSH replication event. Source: com.couchbase.lite.replicator.Replication@1224b507 Transition: IDLE -> OFFLINE Total changes: 0 Completed changes: 0
12:53:07.797 [CBLManagerWorkExecutor] DEBUG c.c.m.s.s.couchbase.CouchbaseService - pull event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@1fcbc8e5 Transition: IDLE -> OFFLINE Total changes: 0 Completed changes: 0
12:53:07.797 [CBLManagerWorkExecutor] DEBUG c.c.m.s.s.couchbase.CouchbaseService - pull event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@1fcbc8e5 Transition: IDLE -> OFFLINE Total changes: 0 Completed changes: 0
12:53:07.797 [CBLManagerWorkExecutor] INFO  c.g.oxo42.stateless4j.StateMachine - Firing RESUME
12:53:07.797 [CBLManagerWorkExecutor] DEBUG c.c.m.s.s.couchbase.CouchbaseService - push event: PUSH replication event. Source: com.couchbase.lite.replicator.Replication@1224b507 Transition: OFFLINE -> STOPPING Total changes: 0 Completed changes: 0
12:53:07.803 [CBLRequestWorker-0c6a4-0] ERROR com.couchbase.lite - Sync: com.couchbase.lite.replicator.ReplicationInternal$4@28306f39 checkSessionAtPath() response: {authentication_handlers=[default, cookie], ok=true, userCtx={channels={*=1}, name=null}}
12:53:07.803 [CBLRequestWorker-0c6a4-0] ERROR com.couchbase.lite - Sync: com.couchbase.lite.replicator.ReplicationInternal$4@28306f39 Exception in checkSessionAtPath()
12:53:07.804 [ChangeTracker-http://localhost:4984/mobicat/] WARN  com.couchbase.lite - ChangeTracker: RemoteRequest Unable to parse user info, not setting credentials
12:53:07.804 [Thread-18] WARN  com.couchbase.lite - Sync: [fireTrigger()] => WAITING_FOR_CHANGES
12:53:07.807 [CBLManagerWorkExecutor] ERROR com.couchbase.lite - Sync: Change tracker stopped during continuous replication
12:53:07.808 [CBLManagerWorkExecutor] WARN  com.couchbase.lite - Sync: [fireTrigger()] => WAITING_FOR_CHANGES
12:53:07.808 [Thread-9] INFO  o.a.coyote.http11.Http11NioProtocol - Pausing ProtocolHandler ["http-nio-8080"]
12:53:07.809 [CBLManagerWorkExecutor] DEBUG c.c.m.s.s.couchbase.CouchbaseService - push event: PUSH replication event. Source: com.couchbase.lite.replicator.Replication@1224b507 Transition: OFFLINE -> STOPPING Total changes: 0 Completed changes: 0
12:53:07.810 [CBLManagerWorkExecutor] INFO  c.g.oxo42.stateless4j.StateMachine - Firing STOP_IMMEDIATE
12:53:07.810 [ChangeTracker-http://localhost:4984/mobicat/] ERROR com.couchbase.lite - Sync: changeTrackerCaughtUp
12:53:07.810 [CBLManagerWorkExecutor] WARN  com.couchbase.lite - Sync: Not attempting to setLastSequence, db is closed
12:53:07.814 [CBLManagerWorkExecutor] DEBUG c.c.m.s.s.couchbase.CouchbaseService - pull event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@1fcbc8e5 Transition: OFFLINE -> STOPPING Total changes: 0 Completed changes: 0
12:53:07.814 [CBLManagerWorkExecutor] DEBUG c.c.m.s.s.couchbase.CouchbaseService - pull event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@1fcbc8e5 Transition: OFFLINE -> STOPPING Total changes: 0 Completed changes: 0
12:53:07.814 [CBLManagerWorkExecutor] INFO  c.g.oxo42.stateless4j.StateMachine - Firing WAITING_FOR_CHANGES
12:53:07.814 [CBLManagerWorkExecutor] INFO  c.g.oxo42.stateless4j.StateMachine - Firing WAITING_FOR_CHANGES
12:53:07.814 [CBLManagerWorkExecutor] DEBUG c.c.m.s.s.couchbase.CouchbaseService - push event: PUSH replication event. Source: com.couchbase.lite.replicator.Replication@1224b507 Transition: STOPPING -> STOPPED Total changes: 0 Completed changes: 0
12:53:07.816 [ChangeTracker-http://localhost:4984/mobicat/] WARN  com.couchbase.lite - ChangeTracker: RemoteRequest Unable to parse user info, not setting credentials
12:53:07.826 [Thread-20] WARN  com.couchbase.lite - Sync: [fireTrigger()] => STOP_IMMEDIATE
12:53:07.827 [ChangeTracker-http://localhost:4984/mobicat/] WARN  com.couchbase.lite - ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@1f15768a: Change tracker calling changeTrackerStopped, client: com.couchbase.lite.replicator.PullerInternal@3134b194
12:53:07.831 [Thread-20] ERROR com.couchbase.lite - Sync: PullerInternal stopGraceful.run() finished
12:53:07.831 [CBLManagerWorkExecutor] INFO  c.g.oxo42.stateless4j.StateMachine - Firing STOP_IMMEDIATE
12:53:07.831 [CBLManagerWorkExecutor] WARN  com.couchbase.lite - Sync: Not attempting to setLastSequence, db is closed
12:53:07.831 [CBLManagerWorkExecutor] ERROR com.couchbase.lite - Sync: Change tracker stopped during continuous replication
12:53:07.831 [CBLManagerWorkExecutor] WARN  com.couchbase.lite - Sync: [fireTrigger()] => WAITING_FOR_CHANGES
12:53:07.832 [CBLManagerWorkExecutor] DEBUG c.c.m.s.s.couchbase.CouchbaseService - pull event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@1fcbc8e5 Transition: STOPPING -> STOPPED Total changes: 0 Completed changes: 0
12:53:07.832 [CBLManagerWorkExecutor] INFO  c.g.oxo42.stateless4j.StateMachine - Firing WAITING_FOR_CHANGES
12:53:07.859 [Thread-9] INFO  o.a.catalina.core.StandardService - Stopping service Tomcat
12:53:07.863 [localhost-startStop-2] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Destroying Spring FrameworkServlet 'dispatcherServlet'
12:53:07.871 [Thread-9] INFO  o.a.coyote.http11.Http11NioProtocol - Stopping ProtocolHandler ["http-nio-8080"]
12:53:07.878 [Thread-9] INFO  o.a.coyote.http11.Http11NioProtocol - Destroying ProtocolHandler ["http-nio-8080"]
12:53:08.322 [Thread-21] ERROR com.couchbase.lite - Sync: batcher.waitForPendingFutures()
12:53:08.322 [Thread-21] ERROR com.couchbase.lite - Sync: waitForPendingFutures()
12:53:09.322 [Thread-21] ERROR com.couchbase.lite - Sync: downloadsToInsert.waitForPendingFutures()
12:53:09.323 [Thread-21] WARN  com.couchbase.lite - Sync: [fireTrigger()] => WAITING_FOR_CHANGES
12:53:09.323 [Thread-21] ERROR com.couchbase.lite - Sync: PullerInternal stopGraceful.run() finished
12:53:09.323 [CBLManagerWorkExecutor] INFO  c.g.oxo42.stateless4j.StateMachine - Firing WAITING_FOR_CHANGES
```

**Comment by hideki** [comment] 2015-03-06 08:34
Hi @Lupen2002 
Could you please provide us more information to reproduce this issue?
For example:
- How does your code create replicators?
- Do you try to close middle of replication?
- Does your code call only Manager.close()?
Thanks!

**Comment by hideki** [comment] 2015-03-06 23:25
I misunderstood the root cause of this issue. Now I can reproduce this issue. Thanks.

**Closed** 2015-03-12 00:19 UTC

**Comment by hideki** [comment] 2015-03-12 00:21
Hi @Lupen2002 
We fixed the issue. https://github.com/couchbase/couchbase-lite-java-core/pull/473
If you have change please try latest codes from master branch.
